# Generated by Django 4.2.3 on 2023-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
